spring:
  application:
    name: config
  cloud:
    config:
      server:
#        \u914D\u7F6E\u653E\u7F6E\u914D\u7F6E\u7684git\u4ED3\u5E93\u5730\u5740
        git:
          uri: https://github.com/beimingyouyu666/springcloud-learn-config.git
          username: beimingyouyu666
          password: yk.80231314
          basedir: D:/learn/codes-mine/springcloud-learn/config/basedir
#  \u6574\u5408rabbitmq\u5B9E\u73B0\u52A8\u6001\u5237\u65B0\u914D\u7F6E
  rabbitmq:
    addresses: 114.215.147.110
    port: 5672
    username: admin
    password: admin

#  \u6307\u5B9A\u670D\u52A1\u7AEF\u53E3
server:
  port: 8080

#\u6307\u5B9A\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
eureka:
  client:
    availability-zones:
      defaultZone: http://localhost:8761/eureka

#logging:
#  level:
#    web: debug
#\u6307\u5B9A\u6253\u5370\u65E5\u5FD7\u7EA7\u522B\uFF0C\u65B9\u4FBF\u6392\u67E5\u95EE\u9898
logging:
  level:
    org.springframework.cloud.bus: debug

#\u5C06 bus-refresh \u63A5\u53E3\u66B4\u9732\u51FA\u6765\uFF0C\u9ED8\u8BA4\u53EA\u66B4\u9732 health\u548Cinfo \u63A5\u53E3
#\u624B\u52A8\u8C03\u7528\u63A5\u53E3\u4E5F\u53EF\u5B9E\u73B0\u914D\u7F6E\u5237\u65B0\uFF0C\u53EA\u662F\u4E0D\u65B9\u4FBF\uFF0C\u4F7F\u7528git \u7684webhooks\u66F4\u65B9\u4FBF
management:
  endpoints:
    web:
      exposure:
        include: "*"
