spring:
  application:
    name: eureka-server

eureka:
  client:
    availability-zones:
      default-Zone: http://localhost:8761/eureka
    # \u6CE8\u518C\u4E2D\u5FC3\u4E0D\u5C06\u81EA\u8EAB\u6CE8\u518C\u4E0A\u53BB -- false
    register-with-eureka: false

server:
  port: 8761