spring:
  application:
    name: eureka-server1

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server2:8762/eureka,http://eureka-server3:8763/eureka
    register-with-eureka: false
    fetch-registry: true

server:
  port: 8761