spring:
  application:
    name: eureka-server3

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:8761/eureka,http://eureka-server2:8762/eureka
    register-with-eureka: false
    fetch-registry: true

server:
  port: 8763