spring:
  application:
    name: product
  datasource:
    username: root
    password: 111111
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.215.147.110:3316/yangk?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  port: 8772
eureka:
  client:
    availability-zones:
      default-Zone: http://localhost:8761/eureka